<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>

		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<AssemblyName>MacroMir4</AssemblyName>
		<RootNamespace>Macro</RootNamespace>
		<ApplicationIcon>Assets\app-v2.ico</ApplicationIcon>

		<!-- Publicação -->
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<SelfContained>true</SelfContained>
		<PublishSingleFile>true</PublishSingleFile>

		<!-- Opcional: reduz um pouco o tamanho -->
		<EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
	</PropertyGroup>

	<!-- Pastas -->
	<ItemGroup>
		<Folder Include="Assets\Fonts\" />
		<Folder Include="Controls\" />
		<Folder Include="Services\Models\" />
	</ItemGroup>

	<!-- Recursos -->
	<ItemGroup>
		<!-- Imagem usada pelo WPF -->
		<Resource Include="Assets\teste.png" />
		<Resource Include="Assets\raid-slide-1.png" />
		<Resource Include="Assets\raid-slide-2.png" />
		<Resource Include="Assets\boss-slide-1.png" />
		<Resource Include="Assets\boss-slide-2.png" />
		<Content Include="Assets\app-icon.png" />
		<Content Include="Assets\app.ico" />
		<Content Include="Assets\Templates\daily-donate.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Assets\Templates\daily-donate-warehouse.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Assets\Templates\daily-donate-button.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Assets\Templates\daily-step-*.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Assets\Templates\daily-flow-*.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Assets\Templates\daily-scroll-*.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Assets\Templates\daily-favorite-*.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Assets\Templates\daily-raid-*.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Assets\Templates\DailyRaid\daily-raid-*.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Assets\Templates\daily-arena-*.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Assets\Templates\daily-arena-*.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Resource Include="Assets\app-v2.ico" />
		<Content Include="Data\bosses.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
	<ItemGroup>
	  <PackageReference Include="OpenCvSharp4" Version="4.11.0.20250507" />
	  <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.11.0.20250507" />
	</ItemGroup>

</Project>
